# -*- coding: utf-8 -*-
"""Tic Tac Toe CSC 120 Sp22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-2sMg4HfQzfB9oqQ9tUvi3rYupnqniqd
"""

myBoard = {'1': ' ' , '2': ' ' , '3': ' ' ,
            '4': ' ' , '5': ' ' , '6': ' ' ,
            '7': ' ' , '8': ' ' , '9': ' ' }

board_keys = []

for key in myBoard:
    board_keys.append(key)

def print_Board(board):
    print(board['1'] + '|' + board['2'] + '|' + board['3'])
    print('-+-+-')
    print(board['4'] + '|' + board['5'] + '|' + board['6'])
    print('-+-+-')
    print(board['7'] + '|' + board['8'] + '|' + board['9'])

def game():

    turn = 'X'
    count = 0

    for i in range(10):
        print_Board(myBoard)
        print("It's your turn, " + turn + ".Where do you want to place your marker?")

        move = input()        

        if myBoard[move] == ' ':
            myBoard[move] = turn
            count += 1
        else:
            print("That place is filled.\nTry again. Move to which place?")
            continue
 
        if count >= 5:
            if myBoard['1'] == myBoard['2'] == myBoard['3'] != ' ': 
                print_Board(myBoard)
                print("\nGame Over.\n")                
                print(" **** " +turn + " won. ****")                
                break
            elif myBoard['4'] == myBoard['5'] == myBoard['6'] != ' ': 
                print_Board(myBoard)
                print("\nGame Over.\n")                
                print(" **** " +turn + " won. ****")
                break
            elif myBoard['7'] == myBoard['8'] == myBoard['9'] != ' ': 
                print_Board(myBoard)
                print("\nGame Over.\n")                
                print(" **** " +turn + " won. ****")
                break
            elif myBoard['7'] == myBoard['4'] == myBoard['1'] != ' ': 
                print_Board(myBoard)
                print("\nGame Over.\n")                
                print(" **** " +turn + " won. ****")
                break
            elif myBoard['8'] == myBoard['5'] == myBoard['2'] != ' ': 
                print_Board(myBoard)
                print("\nGame Over.\n")                
                print(" **** " +turn + " won. ****")
                break
            elif myBoard['9'] == myBoard['6'] == myBoard['3'] != ' ': 
                print_Board(myBoard)
                print("\nGame Over.\n")                
                print(" **** " +turn + " won. ****")
                break 
            elif myBoard['3'] == myBoard['5'] == myBoard['7'] != ' ': 
                print_Board(myBoard)
                print("\nGame Over.\n")                
                print(" **** " +turn + " won. ****")
                break
            elif myBoard['9'] == myBoard['5'] == myBoard['1'] != ' ': 
                print_Board(myBoard)
                print("\nGame Over.\n")                
                print(" **** " +turn + " won. ****")
                break 

        
        if count == 9:
            print("\nGame Over.\n")                
            print("It's a Tie!")

        if turn =='X':
            turn = 'O'
        else:
            turn = 'X'        
    
    restart = input("Would you like to play Again?(y/n)")
    if restart == "y" or restart == "Y":  
        for key in board_keys:
            myBoard[key] = " "

        game()

if __name__ == "__main__":
    game()